### ISSUE TITLE
Crash while undoing rotate and raise/lower changes to hyper tube support

### ISSUE THREAD

**Issue by pixelmosh** [TwoTwoEleven/MicroManage#1]
MicroManage version 0.9.2

Game crashed to desktop with the following error:

    Version: 125236, IsEditor: No, IsPerforceBuild: No, BuildConfiguration: Shipping, Launcher: Steam, NetMode: Listen Server, IsUsingMods: Yes

    Assertion failed: StartIndex >= 0 && StartIndex <= Array.Num() [File:d:\ws\sb-200518130817-657\ue4\engine\source\runtime\core\public\Containers/BitArray.h] [Line: 947]

    FactoryGame_Win64_Shipping!FWindowsErrorOutputDevice::Serialize() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\core\private\windows\windowserroroutputdevice.cpp:79]
    FactoryGame_Win64_Shipping!FOutputDevice::LogfImpl() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\core\private\misc\outputdevice.cpp:71]
    FactoryGame_Win64_Shipping!AssertFailedImplV() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\core\private\misc\assertionmacros.cpp:101]
    FactoryGame_Win64_Shipping!FDebug::CheckVerifyFailedImpl() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\core\private\misc\assertionmacros.cpp:439]
    FactoryGame_Win64_Shipping!AActor::GetComponentsByClass() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\engine\private\actor.cpp:2854]
    UE4_MicroManage_Win64_Shipping!UMicroManageRCO::ServerUndoAction_Implementation() [c:\projects\satisfactory\mm220\source\micromanage\micromanagerco.cpp:89]
    UE4_MicroManage_Win64_Shipping!UMicroManageRCO::execServerUndoAction() [c:\projects\satisfactory\mm220\source\micromanage\micromanagerco.h:12]
    FactoryGame_Win64_Shipping!UFunction::Invoke() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\coreuobject\private\uobject\class.cpp:4644]
    FactoryGame_Win64_Shipping!UObject::ProcessEvent() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\coreuobject\private\uobject\scriptcore.cpp:1464]
    UE4_MicroManage_Win64_Shipping!UMicroManageRCO::ServerUndoAction() [c:\projects\satisfactory\mm220\intermediate\build\win64\ue4\inc\micromanage\micromanagerco.gen.cpp:72]
    UE4_MicroManage_Win64_Shipping!UMicroManageAction::PerformUndo() [c:\projects\satisfactory\mm220\source\micromanage\micromanageaction.cpp:44]
    UE4_MicroManage_Win64_Shipping!UMicroManageInput::PerformIndexedAction() [c:\projects\satisfactory\mm220\source\micromanage\micromanageinput.cpp:93]
    UE4_MicroManage_Win64_Shipping!TBaseFunctorDelegateInstance<TTypeWrapper<void> __cdecl(FKey),<lambda_4741c2653dce5e51f6de03de1b4387a7> >::Execute() [c:\program files\unreal engine - css\engine\source\runtime\core\public\delegates\delegateinstancesimpl.h:893]
    FactoryGame_Win64_Shipping!FInputActionUnifiedDelegate::Execute() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\engine\classes\components\inputcomponent.h:261]
    FactoryGame_Win64_Shipping!UPlayerInput::ProcessInputStack() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\engine\private\userinterface\playerinput.cpp:1310]
    FactoryGame_Win64_Shipping!APlayerController::ProcessPlayerInput() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\engine\private\playercontroller.cpp:2476]
    FactoryGame_Win64_Shipping!APlayerController::TickPlayerInput() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\engine\private\playercontroller.cpp:4461]
    FactoryGame_Win64_Shipping!APlayerController::PlayerTick() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\engine\private\playercontroller.cpp:2134]
    FactoryGame_Win64_Shipping!AFGPlayerController::PlayerTick() [d:\ws\sb-200518130817-657\ue4\games\factorygame\source\factorygame\private\fgplayercontroller.cpp:219]
    FactoryGame_Win64_Shipping!APlayerController::TickActor() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\engine\private\playercontroller.cpp:4601]
    FactoryGame_Win64_Shipping!FActorTickFunction::ExecuteTick() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\engine\private\actor.cpp:167]
    FactoryGame_Win64_Shipping!FTickFunctionTask::DoTask() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\engine\private\ticktaskmanager.cpp:290]
    FactoryGame_Win64_Shipping!TGraphTask<FTickFunctionTask>::ExecuteTask() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\core\public\async\taskgraphinterfaces.h:847]
    FactoryGame_Win64_Shipping!FNamedTaskThread::ProcessTasksUntilQuit() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\core\private\async\taskgraph.cpp:581]
    FactoryGame_Win64_Shipping!FTaskGraphImplementation::WaitUntilTasksComplete() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\core\private\async\taskgraph.cpp:1457]
    FactoryGame_Win64_Shipping!FTickTaskSequencer::ReleaseTickGroup() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\engine\private\ticktaskmanager.cpp:561]
    FactoryGame_Win64_Shipping!FTickTaskManager::RunTickGroup() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\engine\private\ticktaskmanager.cpp:1517]
    FactoryGame_Win64_Shipping!UWorld::Tick() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\engine\private\leveltick.cpp:1568]
    FactoryGame_Win64_Shipping!UGameEngine::Tick() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\engine\private\gameengine.cpp:1366]
    FactoryGame_Win64_Shipping!UFGGameEngine::Tick() [d:\ws\sb-200518130817-657\ue4\games\factorygame\source\factorygame\private\fggameengine.cpp:9]
    FactoryGame_Win64_Shipping!FEngineLoop::Tick() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\launch\private\launchengineloop.cpp:4028]
    FactoryGame_Win64_Shipping!GuardedMain() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\launch\private\launch.cpp:168]
    FactoryGame_Win64_Shipping!GuardedMainWrapper() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\launch\private\windows\launchwindows.cpp:145]
    FactoryGame_Win64_Shipping!WinMain() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\launch\private\windows\launchwindows.cpp:275]
    FactoryGame_Win64_Shipping!__scrt_common_main_seh() [d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288]
    kernel32
    ntdll

**Comment by TwoTwoEleven** [comment]
Fixed in the 0.9.3 release.  Thanks for the bug report.
