### ISSUE TITLE
Staisfactory won't start SML 3.1.0 and CL152331. Not Exerimetnal

### ISSUE THREAD

**Issue by Tsyklop** [TwoTwoEleven/MicroManage#10]
I have an error like these:
https://github.com/TwoTwoEleven/MicroManage/issues/8
https://github.com/TwoTwoEleven/MicroManage/issues/7

Mod version 0.9.6.
SMM 2.4.4
SML 3.1.0

**Comment by parkerault** [comment]
Me too. The update 0.4.2.3 released a few hours ago moved the patches from the latest experimental build into early access.

**Comment by TwoTwoEleven** [comment]
Version 0.9.7, released May 13th, added compatibility for SML 3.1 on EA and EXP game versions
