### ISSUE TITLE
U6 Failing

### ISSUE THREAD

**Issue by tylerlazenby** [TwoTwoEleven/MicroManage#23]
This mod is failing to load and the game crashed on start.

"Plugin 'MicroManage' failed to load because module 'MicroManage' could not be loaded. There may be an operating system error or the module may not be properly set up". This is happening after updating to U6 Experimental.

**Comment by Vergeh** [comment]
I am experiencing this after updating to U6 as well.

**Comment by davidnyhuis** [comment]
It looks like the Satisfactory Mod Loader (SML) build needs to be updated before this mod can be updated. The mod author has already replied on the Satisfactory Modding Discord server that there are plans to update this mod for Satisfactory Update 6 Experimental Build.

There is no ETA on the SML delivery date.

**Comment by TwoTwoEleven** [comment]
SML has been updated for Update 6 Experimental and the 0.9.12 release of Micro Manage has been released to support it
