### ISSUE TITLE
latest build breaks micro manage

### ISSUE THREAD

**Issue by BoeNana** [TwoTwoEleven/MicroManage#24]
after update the mod is not working sadly. 
thank you for your mod, I use it all the time.

**Comment by crsmithdev** [comment]
Specifically, in the new v0.6.0.10 release, when the tool is equipped, the hints don't display and none of the key combinations seem to function.

**Comment by TwoTwoEleven** [comment]
This is fixed in the 1.0.2 release.  Thanks for the report and enjoy!
