### ISSUE TITLE
Crash on start on latest version

### ISSUE THREAD

**Issue by vyachesIavskiy** [TwoTwoEleven/MicroManage#6]
After updating to latest version (CL151024, I'm using Experimental version) I got this crash when I start a game
![image](https://user-images.githubusercontent.com/5702421/115392923-c802a300-a1e9-11eb-81df-4396ab32495e.png)

**Comment by vyachesIavskiy** [comment]
Точка вход в процедуру = Entry point of the procedure
не найдена в библиотеке = was on found in the library

**Comment by Maverik666** [comment]
Since yeterdays update i have the same problem
![image](https://user-images.githubusercontent.com/82930102/115507297-3bed8b80-a27c-11eb-84f5-d730faef9178.png)

**Comment by TwoTwoEleven** [comment]
Fixed in the 0.9.6 release.
