### ISSUE TITLE
Game crashes anyone trying to join Multiplayer

### ISSUE THREAD

**Issue by Nevynx** [TwoTwoEleven/MicroManage#9]
When any client attempts to join a hosted game they are  crashing back to desktop.
Here is a screenshot of the error that appears after they crash.

![Screenshot_1964](https://user-images.githubusercontent.com/12294237/117213257-b69ed500-ae3e-11eb-860b-b02e89b0f1b1.png)

**Comment by TwoTwoEleven** [comment]
SML 3.0 was incompatible with multiplayer.  SML 3.1.x with Micro Manage 0.9.7 or later should allow multi-player now
